In [30]:
import pandas as pd

In [31]:
dataset = pd.read_csv("data/participant_data.csv")

In [32]:
dataset.head(5)

,timestamp,ai_use,baseline_trust,comfort,selected_task,decision_confidence,ai_influence,trust_1,trust_2,trust_3,transparency_1,transparency_2,ux_1,ux_2,open_trust,open_explanation,open_improvement,condition_key
0,2026-05-31T18:27:26.562435-07:00,5,2,1,Organize Notes,2,2,2,1,3,6,1,2,3,NaN,NaN,NaN,minimal_explanation
1,2026-05-31T21:41:43.277062-07:00,6,6,6,Draft Project Report,7,6,6,6,6,7,7,7,7,The advice AI gave just made sense and there w...,"Helpful,",If you really want to know how much AI has an ...,transparent_explanation
2,2026-05-31T21:50:50.663039-07:00,4,4,4,Draft Project Report,7,2,6,4,4,7,7,7,4,The AI had sound reasoning to support its reco...,It felt helpful,It would help to go through a few examples to ...,uncertainty_calibrated
3,2026-05-31T22:22:57.495345-07:00,5,4,5,Draft Project Report,5,4,1,1,1,4,5,6,5,NaN,NaN,NaN,high_confidence
4,2026-06-02T10:44:18.296014-07:00,6,5,7,Review Course Module,7,1,7,7,7,7,6,7,7,The ai singled out the most urgent task accura...,"The explanation was clear, coherent and accura...",adding condiitons to recommendations would mak...,high_confidence

In [33]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   timestamp            21 non-null     str
 1   ai_use               21 non-null     int64
 2   baseline_trust       21 non-null     int64
 3   comfort              21 non-null     int64
 4   selected_task        20 non-null     str
 5   decision_confidence  21 non-null     int64
 6   ai_influence         21 non-null     int64
 7   trust_1              21 non-null     int64
 8   trust_2              21 non-null     int64
 9   trust_3              21 non-null     int64
 10  transparency_1       21 non-null     int64
 11  transparency_2       21 non-null     int64
 12  ux_1                 21 non-null     int64
 13  ux_2                 21 non-null     int64
 14  open_trust           15 non-null     str
 15  open_explanation     15 non-null     str
 16  open_improvement     12 non-null     str
 17  condition_key        21 non-null     str
dtypes: int64(12), str(6)
memory usage: 7.2 KB

In [34]:
dataset.isnull().sum()

timestamp              0
ai_use                 0
baseline_trust         0
comfort                0
selected_task          1
decision_confidence    0
ai_influence           0
trust_1                0
trust_2                0
trust_3                0
transparency_1         0
transparency_2         0
ux_1                   0
ux_2                   0
open_trust             6
open_explanation       6
open_improvement       9
condition_key          0
dtype: int64

In [35]:
dataset["trust_score"] = ((dataset["trust_1"] + 
                          dataset["trust_2"] + 
                          dataset["trust_3"]) / 3).round(2)

In [36]:
dataset['transparency_score'] = ((dataset ["transparency_1"] + 
                                   dataset ["transparency_2"]) / 2).round(2)

In [37]:
dataset['ux_score'] = ((dataset ['ux_1'] + dataset ['ux_2'])/2).round (2)

In [38]:
dataset

,timestamp,ai_use,baseline_trust,comfort,selected_task,decision_confidence,ai_influence,trust_1,trust_2,trust_3,...,transparency_2,ux_1,ux_2,open_trust,open_explanation,open_improvement,condition_key,trust_score,transparency_score,ux_score
0,2026-05-31T18:27:26.562435-07:00,5,2,1,Organize Notes,2,2,2,1,3,...,1,2,3,NaN,NaN,NaN,minimal_explanation,2.00,3.5,2.5
1,2026-05-31T21:41:43.277062-07:00,6,6,6,Draft Project Report,7,6,6,6,6,...,7,7,7,The advice AI gave just made sense and there w...,"Helpful,",If you really want to know how much AI has an ...,transparent_explanation,6.00,7.0,7.0
2,2026-05-31T21:50:50.663039-07:00,4,4,4,Draft Project Report,7,2,6,4,4,...,7,7,4,The AI had sound reasoning to support its reco...,It felt helpful,It would help to go through a few examples to ...,uncertainty_calibrated,4.67,7.0,5.5
3,2026-05-31T22:22:57.495345-07:00,5,4,5,Draft Project Report,5,4,1,1,1,...,5,6,5,NaN,NaN,NaN,high_confidence,1.00,4.5,5.5
4,2026-06-02T10:44:18.296014-07:00,6,5,7,Review Course Module,7,1,7,7,7,...,6,7,7,The ai singled out the most urgent task accura...,"The explanation was clear, coherent and accura...",adding condiitons to recommendations would mak...,high_confidence,7.00,6.5,7.0
5,2026-06-04T09:00:47.387333-07:00,4,3,1,Draft Project Report,6,6,3,4,4,...,5,5,4,NaN,NaN,NaN,uncertainty_calibrated,3.67,5.0,4.5
6,2026-06-05T19:58:39.230101-07:00,7,2,5,Draft Project Report,7,1,6,2,2,...,3,2,1,"My baseline trust in the AI is very low, and I...","The explanation felt excessive, going beyond t...",More data points.,transparent_explanation,3.33,3.0,1.5
7,2026-06-05T20:10:57.753203-07:00,3,2,1,Draft Project Report,7,1,7,7,7,...,7,7,1,NaN,NaN,NaN,high_confidence,7.00,7.0,4.0
8,2026-06-05T20:10:03.856211-07:00,7,5,6,Draft Project Report,7,1,4,6,2,...,2,5,1,NaN,NaN,NaN,uncertainty_calibrated,4.00,2.0,3.0
9,2026-06-05T20:14:12.531706-07:00,7,7,5,Draft Project Report,7,1,1,1,1,...,1,1,1,I’d never use AI in that situation,Irrelevant,Nothing,transparent_explanation,1.00,1.0,1.0
10,2026-06-06T07:06:48.708648-07:00,7,5,6,Draft Project Report,6,5,5,3,4,...,2,4,5,The use of word “moderately” made it feel less...,"Felt redundant, not adding much insight","If it’s a simple decision, don’t use excessive...",uncertainty_calibrated,4.00,3.0,4.5
11,2026-06-08T11:45:54.108634-07:00,7,7,6,NaN,6,6,1,1,7,...,7,7,7,Quick and straight to the point. Always seems ...,Helpful,I assume AI will only get smarter or more elab...,minimal_explanation,3.00,7.0,7.0
12,2026-06-08T12:08:40.540869-07:00,4,6,5,Draft Project Report,7,1,7,5,6,...,7,7,7,NaN,NaN,NaN,uncertainty_calibrated,6.00,7.0,7.0
13,2026-06-08T16:21:43.249518-07:00,5,3,3,Draft Project Report,4,3,5,5,5,...,7,5,5,Followed logic that was not foreign to me,Helpful,"Not sure exactly, I use as a guide and informa...",minimal_explanation,5.00,6.0,5.0
14,2026-06-09T09:09:34.148940-07:00,7,4,7,Reply to Emails,7,3,5,6,6,...,6,7,3,It was not trustworthy because it suggested an...,The explanation was helpful.,NaN,minimal_explanation,5.67,4.0,5.0
15,2026-06-09T14:35:46.484274-07:00,5,6,6,Reply to Emails,4,4,1,1,1,...,6,5,6,My understanding of AI is that it pulls materi...,"Yes, the table was helpful in displaying what ...",It would’ve been nice to have a sentence or tw...,high_confidence,1.00,3.5,5.5
16,2026-06-09T22:28:10.979939-07:00,7,5,6,Review Course Module,7,6,1,1,1,...,4,7,1,clear and logical answer made it feel trustwo...,insufficient,if the ai went into some what if scenario reas...,uncertainty_calibrated,1.00,2.5,4.0
17,2026-06-10T11:00:14.187901-07:00,7,4,6,Draft Project Report,6,2,1,1,1,...,1,1,1,It was not trustworthy but its decision concur...,There was no explanation.,An explanation.,high_confidence,1.00,1.0,1.0
18,2026-06-10T22:12:55.399819-07:00,3,5,3,Draft Project Report,6,2,7,7,7,...,4,6,2,The answer was concise and agreed with the int...,"It felt appropriate for the scenario given, al...",NaN,high_confidence,7.00,5.5,4.0
19,2026-06-11T17:54:11.453924-07:00,5,4,3,Draft Project Report,7,2,4,6,6,...,6,7,2,It explained the reasoning,Helpful,NaN,transparent_explanation,5.33,6.5,4.5
20,2026-06-12T16:40:35.619316-07:00,4,4,7,Review Course Module,4,1,4,4,3,...,1,3,4,"""Clearly"" is a red flag",Insufficient,More details in the context,high_confidence,3.67,2.5,3.5

In [39]:
dataset['timestamp'] = pd.to_datetime(dataset['timestamp'], utc=True)
dataset['timestamp'].info()

<class 'pandas.Series'>
RangeIndex: 21 entries, 0 to 20
Series name: timestamp
Non-Null Count  Dtype
--------------  -----
21 non-null     datetime64[us, UTC]
dtypes: datetime64[us, UTC](1)
memory usage: 300.0 bytes

In [40]:
dataset.columns

Index(['timestamp', 'ai_use', 'baseline_trust', 'comfort', 'selected_task',
       'decision_confidence', 'ai_influence', 'trust_1', 'trust_2', 'trust_3',
       'transparency_1', 'transparency_2', 'ux_1', 'ux_2', 'open_trust',
       'open_explanation', 'open_improvement', 'condition_key', 'trust_score',
       'transparency_score', 'ux_score'],
      dtype='str')

In [41]:
dataset['selected_task'] = dataset['selected_task'].fillna('missing')
dataset['selected_task']

0           Organize Notes
1     Draft Project Report
2     Draft Project Report
3     Draft Project Report
4     Review Course Module
5     Draft Project Report
6     Draft Project Report
7     Draft Project Report
8     Draft Project Report
9     Draft Project Report
10    Draft Project Report
11                 missing
12    Draft Project Report
13    Draft Project Report
14         Reply to Emails
15         Reply to Emails
16    Review Course Module
17    Draft Project Report
18    Draft Project Report
19    Draft Project Report
20    Review Course Module
Name: selected_task, dtype: str

In [42]:
cols = ['open_trust', 'open_explanation', 'open_improvement']
dataset[cols] = dataset[cols].apply(lambda col: col.str.strip()).fillna('no_response')
dataset[cols]

,open_trust,open_explanation,open_improvement
0,no_response,no_response,no_response
1,The advice AI gave just made sense and there w...,"Helpful,",If you really want to know how much AI has an ...
2,The AI had sound reasoning to support its reco...,It felt helpful,It would help to go through a few examples to ...
3,no_response,no_response,no_response
4,The ai singled out the most urgent task accura...,"The explanation was clear, coherent and accurate.",adding condiitons to recommendations would mak...
5,no_response,no_response,no_response
6,"My baseline trust in the AI is very low, and I...","The explanation felt excessive, going beyond t...",More data points.
7,no_response,no_response,no_response
8,no_response,no_response,no_response
9,I’d never use AI in that situation,Irrelevant,Nothing
10,The use of word “moderately” made it feel less...,"Felt redundant, not adding much insight","If it’s a simple decision, don’t use excessive..."
11,Quick and straight to the point. Always seems ...,Helpful,I assume AI will only get smarter or more elab...
12,no_response,no_response,no_response
13,Followed logic that was not foreign to me,Helpful,"Not sure exactly, I use as a guide and informa..."
14,It was not trustworthy because it suggested an...,The explanation was helpful.,no_response
15,My understanding of AI is that it pulls materi...,"Yes, the table was helpful in displaying what ...",It would’ve been nice to have a sentence or tw...
16,clear and logical answer made it feel trustwo...,insufficient,if the ai went into some what if scenario reas...
17,It was not trustworthy but its decision concur...,There was no explanation.,An explanation.
18,The answer was concise and agreed with the int...,"It felt appropriate for the scenario given, al...",no_response
19,It explained the reasoning,Helpful,no_response
20,"""Clearly"" is a red flag",Insufficient,More details in the context

In [46]:
dataset['followed_ai'] = dataset['selected_task'] == "Draft Project Report"

In [47]:
dataset

,timestamp,ai_use,baseline_trust,comfort,selected_task,decision_confidence,ai_influence,trust_1,trust_2,trust_3,...,ux_1,ux_2,open_trust,open_explanation,open_improvement,condition_key,trust_score,transparency_score,ux_score,followed_ai
0,2026-06-01 01:27:26.562435+00:00,5,2,1,Organize Notes,2,2,2,1,3,...,2,3,no_response,no_response,no_response,minimal_explanation,2.00,3.5,2.5,False
1,2026-06-01 04:41:43.277062+00:00,6,6,6,Draft Project Report,7,6,6,6,6,...,7,7,The advice AI gave just made sense and there w...,"Helpful,",If you really want to know how much AI has an ...,transparent_explanation,6.00,7.0,7.0,True
2,2026-06-01 04:50:50.663039+00:00,4,4,4,Draft Project Report,7,2,6,4,4,...,7,4,The AI had sound reasoning to support its reco...,It felt helpful,It would help to go through a few examples to ...,uncertainty_calibrated,4.67,7.0,5.5,True
3,2026-06-01 05:22:57.495345+00:00,5,4,5,Draft Project Report,5,4,1,1,1,...,6,5,no_response,no_response,no_response,high_confidence,1.00,4.5,5.5,True
4,2026-06-02 17:44:18.296014+00:00,6,5,7,Review Course Module,7,1,7,7,7,...,7,7,The ai singled out the most urgent task accura...,"The explanation was clear, coherent and accurate.",adding condiitons to recommendations would mak...,high_confidence,7.00,6.5,7.0,False
5,2026-06-04 16:00:47.387333+00:00,4,3,1,Draft Project Report,6,6,3,4,4,...,5,4,no_response,no_response,no_response,uncertainty_calibrated,3.67,5.0,4.5,True
6,2026-06-06 02:58:39.230101+00:00,7,2,5,Draft Project Report,7,1,6,2,2,...,2,1,"My baseline trust in the AI is very low, and I...","The explanation felt excessive, going beyond t...",More data points.,transparent_explanation,3.33,3.0,1.5,True
7,2026-06-06 03:10:57.753203+00:00,3,2,1,Draft Project Report,7,1,7,7,7,...,7,1,no_response,no_response,no_response,high_confidence,7.00,7.0,4.0,True
8,2026-06-06 03:10:03.856211+00:00,7,5,6,Draft Project Report,7,1,4,6,2,...,5,1,no_response,no_response,no_response,uncertainty_calibrated,4.00,2.0,3.0,True
9,2026-06-06 03:14:12.531706+00:00,7,7,5,Draft Project Report,7,1,1,1,1,...,1,1,I’d never use AI in that situation,Irrelevant,Nothing,transparent_explanation,1.00,1.0,1.0,True
10,2026-06-06 14:06:48.708648+00:00,7,5,6,Draft Project Report,6,5,5,3,4,...,4,5,The use of word “moderately” made it feel less...,"Felt redundant, not adding much insight","If it’s a simple decision, don’t use excessive...",uncertainty_calibrated,4.00,3.0,4.5,True
11,2026-06-08 18:45:54.108634+00:00,7,7,6,missing,6,6,1,1,7,...,7,7,Quick and straight to the point. Always seems ...,Helpful,I assume AI will only get smarter or more elab...,minimal_explanation,3.00,7.0,7.0,False
12,2026-06-08 19:08:40.540869+00:00,4,6,5,Draft Project Report,7,1,7,5,6,...,7,7,no_response,no_response,no_response,uncertainty_calibrated,6.00,7.0,7.0,True
13,2026-06-08 23:21:43.249518+00:00,5,3,3,Draft Project Report,4,3,5,5,5,...,5,5,Followed logic that was not foreign to me,Helpful,"Not sure exactly, I use as a guide and informa...",minimal_explanation,5.00,6.0,5.0,True
14,2026-06-09 16:09:34.148940+00:00,7,4,7,Reply to Emails,7,3,5,6,6,...,7,3,It was not trustworthy because it suggested an...,The explanation was helpful.,no_response,minimal_explanation,5.67,4.0,5.0,False
15,2026-06-09 21:35:46.484274+00:00,5,6,6,Reply to Emails,4,4,1,1,1,...,5,6,My understanding of AI is that it pulls materi...,"Yes, the table was helpful in displaying what ...",It would’ve been nice to have a sentence or tw...,high_confidence,1.00,3.5,5.5,False
16,2026-06-10 05:28:10.979939+00:00,7,5,6,Review Course Module,7,6,1,1,1,...,7,1,clear and logical answer made it feel trustwo...,insufficient,if the ai went into some what if scenario reas...,uncertainty_calibrated,1.00,2.5,4.0,False
17,2026-06-10 18:00:14.187901+00:00,7,4,6,Draft Project Report,6,2,1,1,1,...,1,1,It was not trustworthy but its decision concur...,There was no explanation.,An explanation.,high_confidence,1.00,1.0,1.0,True
18,2026-06-11 05:12:55.399819+00:00,3,5,3,Draft Project Report,6,2,7,7,7,...,6,2,The answer was concise and agreed with the int...,"It felt appropriate for the scenario given, al...",no_response,high_confidence,7.00,5.5,4.0,True
19,2026-06-12 00:54:11.453924+00:00,5,4,3,Draft Project Report,7,2,4,6,6,...,7,2,It explained the reasoning,Helpful,no_response,transparent_explanation,5.33,6.5,4.5,True
20,2026-06-12 23:40:35.619316+00:00,4,4,7,Review Course Module,4,1,4,4,3,...,3,4,"""Clearly"" is a red flag",Insufficient,More details in the context,high_confidence,3.67,2.5,3.5,False

In [49]:
dataset.to_csv("data/participant_data_cleaned.csv", index=False)